"""The story page must not drift from the written record.

story/src/data/evidence.json is generated by story/scripts/build_data.py. These tests pin its headline numbers to the
committed tables in experiments/results/results.md, and check that each figure quoted from the docs is
still stated there.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "story" / "src" / "data" / "evidence.json"
RESULTS = ROOT / "experiments" / "results" / "results.md"

pytestmark = pytest.mark.skipif(not DATA.exists(), reason="run python story/scripts/build_data.py first")

SYSTEMS = {"B2": "B2 restart", "B3a": "B3a replan, no reconciler", "B3b": "B3b replan, order diff", "TF": "TaskFlux"}


def _data() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def _rows(heading: str, first_col: int = 0) -> list[list[str]]:
    """Cells of every table row between `heading` and the next heading."""
    text = RESULTS.read_text(encoding="utf-8")
    start = text.index(heading)
    end = min([i for i in (text.find("\n**", start + len(heading)), text.find("\n## ", start + len(heading))) if i != -1] or [len(text)])
    return [[c.strip() for c in ln.strip().strip("|").split("|")] for ln in text[start:end].splitlines() if ln.startswith("|") and not ln.startswith("|---")]


def _pct(cell: str) -> float:
    return float(cell.split("%")[0]) / 100


@pytest.mark.parametrize("stage,n", [("truncation", 1500), ("undo", 1200), ("irreversible", 300)])
def test_e1_gearbox_numbers_match_results_md(stage, n):
    rows = {r[0]: r for r in _rows(f"**gearbox, stage = {stage}** ({n} episodes per system)")}
    got = _data()["results"][stage]
    for key, label in SYSTEMS.items():
        r = rows[label]
        assert got[key]["n"] == n
        assert got[key]["success"] == pytest.approx(_pct(r[2]), abs=0.0006), (stage, key, "success")
        assert got[key]["lost"] == pytest.approx(_pct(r[6]), abs=0.006), (stage, key, "destroyed")
        secs = r[-1]
        assert got[key]["time"] == (None if secs == "-" else int(secs)), (stage, key, "time")


def test_e8_perception_numbers_match_results_md():
    text = RESULTS.read_text(encoding="utf-8")
    e8 = text[text.index("## E8"):]
    syn = e8[e8.index("**synthetic**"):]
    rows = [[c.strip() for c in ln.strip().strip("|").split("|")] for ln in syn.splitlines() if ln.startswith("| 0.05 |")]
    by_policy = {r[1]: r for r in rows}
    got = _data()["perception"]
    for pol in ("trust", "consistency", "inspect_undo", "inspect_critical", "inspect_all"):
        r = by_policy[pol]
        assert got[pol]["success"] == pytest.approx(_pct(r[3]), abs=0.0006), pol
        assert got[pol]["inspections"] == pytest.approx(float(r[6]), abs=0.05), pol


def test_quoted_facts_are_still_in_the_docs():
    facts = _data()["facts"]
    for name, f in facts.items():
        if "quote" not in f:
            continue
        doc = (ROOT / f["source"]).read_text(encoding="utf-8")
        assert f["quote"] in doc, f"{name}: {f['quote']!r} not found in {f['source']}"


def test_test_count_is_plausible():
    assert _data()["facts"]["tests"]["value"] >= 200


def test_story_copy_has_no_em_dashes():
    src = ROOT / "story" / "src"
    for f in list(src.glob("*.jsx")) + [src / "styles.css"]:
        assert not re.search("[–—]", f.read_text(encoding="utf-8")), f"dash in {f.name}"
